/**
@mainpage
@author Artem Kasyanov
@date 20.12.2020
@version 1.0
*/
#include <stdio.h>
#define N 6
/**
@brief This function determines whether a given ticket is lucky or not.
The procedure is as follows:
	- A loop is created that will process the number bit by bit as long as it exists.
	- Each digit of the number is counted separately and converted into units.
	- The sum of the first three and last three digits is calculated.
	- If sum1 and sum2 are the same, this ticket is lucky!
	- After all iterations, the value * lucky * is returned, which can be 0 or 1.
@param[in] number The first argument is written to this parameter.
*/
int luckycount(int number){
	int lucky=0,sum1=0,sum2=0,mainperem=number,perem1=10,perem2=0,counter=0;
	for(counter;counter<=N;counter++){ /*The loop which counter sum1 and sum2*/
		if(counter<(N/2)){
			perem2=mainperem%perem1;
			mainperem=mainperem/perem1;
			sum1=sum1+perem2;
		}
		else if(counter>(N/2)){
			perem2=mainperem%perem1;
			mainperem=mainperem/perem1;
			sum2=sum2+perem2;	
		}
	}
	if(sum1==sum2){
		lucky=1;
	}
	else{
		lucky=0;
	}
	return lucky;
	
}
/**
@brief This is a normal int main, which specifies a six-digit number, and the second six-digit number is generated by a pseudo-random number generator, after which a function is called to determine whether the ticket is lucky or not.
*/
int main(){
	srand(time(NULL));
	int first=194707,second=rand()%900000+100000,lucky1,lucky2;
	lucky1=luckycount(first);
	lucky2=luckycount(second);
	return 0;
}
